resources:
  reddit_client:
    config:
      client_id:
        env: REDDIT_CLIENT_ID
      client_secret:
        env: REDDIT_CLIENT_SECRET
      username:
        env: REDDIT_USERNAME
      password:
        env: REDDIT_PASSWORD
